name: build-and-push-image
run-name: Build and Push Container image to Amazon ECR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        default: ''
        required: true
        type: string

jobs:
  set-vars:
    runs-on: ubuntu-latest

    # Configuration for dependent jobs to use ${{ needs.set-vars.outputs.tag }}
    outputs:
      tag: ${{ steps.set-vars.outputs.tag }}

    steps:
      - name: Set Variables Based on Event
        id: set-vars
        # Configuration for the set-vars job to produce "${{ steps.set-vars.outputs.tag }}"
        run: |
          tag=""
          if [ "${{ github.event_name }}" == "push" ]; then
            tag=${GITHUB_REF#refs/tags/}
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            tag=${{ inputs.tag }}
          else
            echo "Error: Unsupported event_name '${{ github.event_name }}'" >&2
            exit 1
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "tag=${tag}"

  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: set-vars
    environment: production
    permissions:
      contents: read
      # This is used to Login to Amazon ECR with OIDC
      # @see https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image
        uses: ./.github/actions/build-image
        with:
          PUSH_IMAGE: true
          IMAGE_TAG: ${{ needs.set-vars.outputs.tag }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_REGISTRY: ${{ secrets.AWS_REGISTRY }}
